vim.keymap.set({ "n", "v", "o", "i" }, "<F1>", "<Nop>", { noremap = true, silent = true, desc = "Unbind F1" })
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]], { noremap = true, silent = true, desc = "Exit terminal mode" })
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { noremap = true, silent = true })
vim.keymap.set("n", "U", "<C-r>", { noremap = true, silent = true, desc = "Redo" })
vim.keymap.set({ "n", "v", "o" }, "§", "^", { noremap = true, silent = true, desc = "Jump to first non-blank (alias for ^)"})
vim.keymap.set({ "n", "v", "o" }, "<C-d>", "<C-d>zz", { noremap = true, silent = true, desc = "Ctrl+d jumps down and centers the cursor" })
vim.keymap.set({ "n", "v", "o" }, "<C-u>", "<C-u>zz", { noremap = true, silent = true, desc = "Ctrl+u jumps down and centers the cursor" })
vim.keymap.set({ "n", "v", "o" }, "ß", "\"+", { noremap = true, silent = true, desc = "Select clipboard register" })
