vim.keymap.set({ "n", "v", "o", "i" }, "<F1>", "<Nop>", { noremap = true, silent = true, desc = "Unbind F1" })
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]], { noremap = true, silent = true, desc = "Exit terminal mode" })
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { noremap = true, silent = true })
vim.keymap.set("n", "U", "<C-r>", { noremap = true, silent = true, desc = "Redo" })
vim.keymap.set({ "n", "v", "o" }, "§", "^", { noremap = true, silent = true, desc = "Jump to first non-blank (alias for ^)"})
vim.keymap.set({ "n", "v", "o" }, "<C-d>", "<C-d>zz", { noremap = true, silent = true, desc = "Ctrl+d jumps down and centers the cursor" })
vim.keymap.set({ "n", "v", "o" }, "<C-u>", "<C-u>zz", { noremap = true, silent = true, desc = "Ctrl+u jumps down and centers the cursor" })
vim.keymap.set({ "n", "v", "o" }, ";", ",", { noremap = true, silent = true, desc = "Swap , and ;" })
vim.keymap.set({ "n", "v", "o" }, ",", ";", { noremap = true, silent = true, desc = "Swap , and ;" })
vim.keymap.set({ "n", "v", "o" }, "<C-Left>", "b", { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "o" }, "<C-Right>", "e", { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "o" }, "<C-Up>", "3k", { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "o" }, "<C-Down>", "3j", { noremap = true, silent = true })
